import './globals.css';
import { DM_Sans } from 'next/font/google';

const inter = DM_Sans({ weight: ['400'], subsets: ['latin'] });

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className + ' bg-gradient-to-l from-gray-50 from-30% via-emerald-50 via-50% to-blue-50 to-70%'}>
        {children}
      </body>
    </html>
  )
}
